#spring:
#  security:
#    user:
#      name: art
#      password: 123

axsoup:
  orders:
    pageSize: 10

---
spring:
  profiles: prod

datasource:
  url: jdbc:postgresql://localhost:5432/axsoupcloud
    username: postgres
    password: postgres

logging:
  level:
    axsoup: WARN

# —пособы активировать профиль prod
#    spring:
#      profiles:
#      active:
#      - prod
#
#      % export SPRING_PROFILES_ACTIVE=prod
#
##      If youТre running the application as an executable JAR file, you might also set the
##      active profile with a command-line argument like this:
#      % java -jar taco-cloud.jar --spring.profiles.active=prod